baseURL = 'https://docs.sportclimbs.uk/'
languageCode = 'en-us'
title = 'Sport Climbs UK docs'

theme = "relearn"

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
themeVariant = "sportclimbs"