baseURL = 'https://docs.sportclimbs.uk/'
languageCode = 'en-us'
title = 'Sport Climbs UK docs'

theme = "relearn"
themeVariant = "blue"

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
themeVariant = "sportclimbs"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    noClasses = true
    style = "monokailight"
    tabWidth = 4